CHANGELOG.md, cloudsmith_cli/cli/config.py, cloudsmith_cli/cli/decorators.py, cloudsmith_cli/core/api/init.py, cloudsmith_cli/data/config.ini
Useful when running in an old/broken environment that doesn't support the latest version of TLS that is required by the Cloudsmith service. Should be used with care.
For example:
`python -m cloudsmith_cli ls packages your-account/your-repo -S`
or
`python -m cloudsmith_cli ls packages your-account/your-repo --without-api-ssl-verify`
=> Added support for turning off SSL verification

CONTRIBUTORS.md, README.md
Based on #16 to extend for Mac OS X and different flavours of Window stoo.
=> Fixed locations of config/credential files in docs

cloudsmith_cli/cli/config.py
[Jira ticket]()
This PR fixes a bug in the CLI's `login` command where config values weren't being automatically inserted into the config files.
This seems to be due to both [config](https://github.com/cloudsmith-io/cloudsmith-cli/blob/master/cloudsmith_cli/data/config.ini) and [credentials](https://github.com/cloudsmith-io/cloudsmith-cli/blob/master/cloudsmith_cli/data/credentials.ini) template files no longer have spaces before the assignment of their values, causing the regex to no longer match those lines, meaning those lines were never replaced.
=> [ENG-199] Include optional space in config replacement regex

CHANGELOG.md, README.md, cloudsmith_cli/cli/commands/__init__.py, cloudsmith_cli/cli/commands/list_.py, cloudsmith_cli/cli/commands/repos.py, cloudsmith_cli/cli/commands/repositories.py, cloudsmith_cli/cli/validators.py, cloudsmith_cli/core/api/repos.py
This PR adds support for creating, retrieving, updating and deleting repositories via the CLI, and aliases the `ls repos` command to `repos ls`.
Examples of commands:
- `cloudsmith repositories list`
- `cloudsmith repos ls namespace`
- `cloudsmith repos get namespace/repo`
- `cloudsmith repos create namespace repo-config.json`
- `cloudsmith repos update namespace/repo repo-config.json`
- `cloudsmith repos rm namespace/repo`
=> [ENG-39] Add repository CRUD to CLI

CHANGELOG.md, requirements/common.in, requirements/development.py2.txt, requirements/development.py3.txt, requirements/production.py2.txt, requirements/production.py3.txt, setup.py
Bumps API version to use latest (contains updated support for Conan)
depends on https://github.com/cloudsmith-io/cloudsmith-api/pull/8
=> [ENG-518] Updated support for Conan

CHANGELOG.md, README.md, cloudsmith_cli/cli/commands/__init__.py, cloudsmith_cli/cli/commands/list_.py, cloudsmith_cli/cli/commands/tags.py, cloudsmith_cli/core/api/packages.py
- Added support for the package tagging API, as five sub-commands here in the CLI:
- `add`: Add tags to a package in a repository.
- `clear`: Clear all existing (non-immutable) tags from a package in a repository.
- `list`:  List tags for a package in a repository.
- `remove`: Remove tags from a package in a repository.
- `replace`: Replace all existing (non-immutable) tags on a package in a repository.
=> ENG-497: Added support for package tagging

.bumpversion.cfg, CHANGELOG.md, README.md, cloudsmith_cli/cli/commands/__init__.py, cloudsmith_cli/cli/commands/quota/__init__.py, cloudsmith_cli/cli/commands/quota/command.py, cloudsmith_cli/cli/commands/quota/history.py, cloudsmith_cli/cli/commands/quota/quota.py, cloudsmith_cli/cli/validators.py, cloudsmith_cli/core/api/quota.py, requirements/common.in, requirements/development.py2.txt, requirements/development.py3.txt, requirements/production.py2.txt, requirements/production.py3.txt
Adds commands for quota limits and history (with oss usage available with the -oss flag) for an organisation. 
```bash
cloudsmith quota limits example-org
cloudsmith quota limits example-org -oss
```
```bash
cloudsmith quota history example-org
cloudsmith quota history example-org -oss
```
=> Add Quota Command's for limits and history

CHANGELOG.md, cloudsmith_cli/cli/commands/push.py, cloudsmith_cli/cli/decorators.py
- Added: The push command will now display how long it took to sync/fail a package upload.
- Changed: The synch wait interval is now a minimum bound, and increases over time.
- Fixed: The synch progress bar will now display immediately, instead of being delayed.
=> Fixed sync wait progress / delay

cloudsmith_cli/cli/config.py, cloudsmith_cli/cli/decorators.py, cloudsmith_cli/cli/utils.py, cloudsmith_cli/core/api/init.py, cloudsmith_cli/core/ratelimits.py, cloudsmith_cli/core/rest.py
- Changed display of rate-limiting, to report upfront when it occurs.
- Removed rate-limiting atexit; it makes more sense to handle this per API call instead.
- Added exception to ignore `Retry-After` headers if `--without-rate-limit` is used (will result in a hard error instead).
For the `atexit` removal; it turns out that `urlib3` handles the `Retry-After` headers sent by the API anyway.
=> Changed display/enforcement of rate-limiting

.circleci/config.yml
Updates our CircleCI docker image to python 3.9, which addresses [this failure](https://app.circleci.com/pipelines/github/cloudsmith-io/cloudsmith-cli/223/workflows/c205d521-fe14-41b8-82bf-deed59fd0fdd/jobs/1010) installing the [`cryptography` package, which now relies on `setuptools_rust`](https://github.com/pyca/cryptography/issues/5753)
=> Update CircleCI docker image to circleci/python:3.9

cloudsmith_cli/cli/commands/metrics/entitlements.py, cloudsmith_cli/cli/commands/metrics/packages.py
Addresses the following error:
```
File "/home/circleci/.local/lib/python2.7/site-packages/cloudsmith_cli/cli/commands/metrics/entitlements.py", line 42
headers = ["Metric", *six.iterkeys(metrics_keys)]
^
SyntaxError: invalid syntax
```
=> Fix Python 2 support for the metrics API

CHANGELOG.md, cloudsmith_cli/cli/commands/push.py
- Fixed issue with sleeping during package push, resulting in the process calling the status endpoint continuously.
Continuously calling the status endpoint will deplete the callers rate-limit budget in the API unnecessarily quick.
=> Fixed issue with sleeping during package push

setup.py
Relax API restrictions to allow installation of newer versions of our API clients.
=> Allow cloudsmith-api <2

cloudsmith_cli/core/api/init.py, cloudsmith_cli/core/api/user.py
This PR adjusts the CLI to support `swagger-codegen`'s newer `Configuration()` style (without the global singleton).
Upstream change was made here https://github.com/swagger-api/swagger-codegen/pull/9130
This change is required due to an upgrade in the `swagger-codegen` version we use to generate our API client libs over in https://github.com/cloudsmith-io/cloudsmith-api/pull/27
=> fix: support new swagger-codegen format for cloudsmith-api

cloudsmith_cli/cli/config.py
Per readme, need to search the current working directory for `config.ini` or `credentials.ini`.
Found that given the cli tool is using the library click-config, I see that it's test cases include a test case that specify '.' in the search path: https://github.com/click-contrib/click-configfile/blob/main/tests/functional/test_basics.py#L89
```python
class ConfigFileProcessor3(ConfigFileReader):
config_files = ["hello3.ini"]
config_searchpath = [".", "config/profile"]
config_section_schemas = [
ConfigSectionSchema1.Hello,
]
```
Thus I added that to the same appropriate place in this repo. I tested this change locally by trying `cloudsmith whoami` and `cloudsmith check service` on master with config files in place. Master did not pick up the values in the config files. I then switched to …
=> HAM-135 - add '.' to config search paths

cloudsmith_cli/core/api/init.py
- The `cloudsmith-api` module contains a few cases where client-side validation isn't being applied correctly. 
- This is temporary solution while we investigate the root cause of the problem.
=> Disable client side validation within the cloudsmith-api.

setup.py
This PR bumps the minimum acceptable version of `click` to `8.0.3`, as some of the newer parts of the API require it.
=> fix: require click 8

cloudsmith_cli/core/api/packages.py
- Recent changes have contributed to a minor difference in `docstring` formatting.
- This change takes into account the new difference. 
For example: 
```
>>> attr = getattr(MavenPackageUploadRequest, "artifact_id")
>>> attr.__doc__
'Gets the artifact_id of this MavenPackageUploadRequest.\n\n        The ID of the artifact.\n\n        :return: The artifact_id of this MavenPackageUploadRequest.\n        :rtype: str\n        '
>>> docs = attr.__doc__.strip().split("\n")
>>> docs[1]
''
```
=> fix: Update generation of format parameter descriptions.

cloudsmith_cli/cli/commands/main.py, cloudsmith_cli/cli/tests/commands/test_main.py
Add a deprecation message to output under Python 2.
The approach here is loosely based on that of pip, more in terms of UX than the implementation.
Users can silence the warning with the `--no-python-version-warning` flag.
=> eng-2352: Add Python 2 deprecation message

cloudsmith_cli/cli/commands/policy/__init__.py, cloudsmith_cli/cli/commands/policy/licence.py, cloudsmith_cli/cli/commands/policy/license.py, cloudsmith_cli/cli/tests/commands/policy/test_licence.py, cloudsmith_cli/core/api/orgs.py
Adds functionality to manage license policies via CLI
=> feat(eng-2261): License policy CLI

CONTRIBUTORS.md, cloudsmith_cli/cli/commands/whoami.py
This should fix an issue we encountered where cloudsmith-cli can't do a whoami on a service account.
=> Issue 115: Set null for name and email so whoami works on service acct

cloudsmith_cli/cli/commands/__init__.py, cloudsmith_cli/cli/commands/upstream.py, cloudsmith_cli/cli/tests/commands/test_upstream.py, cloudsmith_cli/cli/tests/conftest.py, cloudsmith_cli/cli/validators.py, cloudsmith_cli/core/api/upstreams.py, requirements/common.in, requirements/development.py2.txt, requirements/development.py3.txt, requirements/production.py2.txt, requirements/production.py3.txt, setup.py
Adds upstream configuration functionality.
=> Eng 2493/upstream config cli

.circleci/config.yml, bin/circle-exec, cloudsmith_cli/cli/tests/commands/policy/test_licence.py, cloudsmith_cli/cli/tests/commands/policy/test_vulnerability.py
For python > 3.8, use circleci's python orb to pytest.
Existing 3.8-based stuff stays as-is, because the python orb doesn't integrate with code climate. (We can change that at a later stage if we want to use something other than code climate which the orb _does_ integrate with.)
Plus a couple of tweaks to tests to not be overly-strict about how many policies exist in an org, now that we're running multiple pytests in parallel. (This could be improved in future if we ever support creating an org from the cli...)
=> chore: test against all supported runtimes

cloudsmith_cli/core/api/init.py, cloudsmith_cli/core/rest.py, cloudsmith_cli/core/tests/test_init.py, cloudsmith_cli/core/tests/test_rest.py, requirements.in, requirements.txt
Added tests for `initialise_api()` and retry functionality in `RestClient.request()`.
I really just wanted to test the retry stuff, but you can't instantiate a rest client without doing the api initialisation first.
Side note:
I found that the more popular requests mocking libraries( e.g. [responses](https://github.com/getsentry/responses/issues/135) and [requests-mock](https://github.com/jamielennox/requests-mock/issues/83)) conflict with retry functionality in our requests adapter, because they too operate (i.e. mock) at the requests adapter level. httpretty operates at the socket level, which makes it possible to test our gear.
=> chore: tests for api init and rest client retry

.pylintrc, CHANGELOG.md, cloudsmith_cli/core/api/exceptions.py, requirements.txt, setup.cfg, setup.py
Cleaned up some more old py2 cruft.
Removed the following packages from setup.py requirements:
- colorama
- future
- simplejson
=> fix: remove unused py2 packages

CHANGELOG.md, cloudsmith_cli/cli/commands/push.py, cloudsmith_cli/cli/tests/commands/test_package_commands.py, cloudsmith_cli/cli/tests/conftest.py, cloudsmith_cli/core/api/files.py
Handle large file uploads transparently in the CLI.
If file size <= `CHUNK_SIZE`, upload it in one go. Progress bar is updated according to bytes uploaded.
If file size > `CHUNK_SIZE`, upload it in chunks. Progress bar is updated according to number of chunks uploaded.
=> feat(eng-1375): Support large file uploads

CHANGELOG.md, CONTRIBUTORS.md, cloudsmith_cli/core/rest.py
Essentially a revert of 101fdeab4ad5fb82215127891ca36610221457cb in which I changed the name of a kwarg supplied to urllib3's `Retry`, as it was issuing a DeprecationWarning.
In hindsight, this was not strictly necessary given that the deprecation is due to take effect in urllib3 2.0, and we currently constrain to < 2.0.
This also caused issues with the 1.1.0 release of cloudsmith-cli in environments where a sufficiently recent version of urllib3 (which accepts the new kwarg name) is not available.
closes #146 #147
=> fix: use method_whitelist kwarg for urllib3 < 2.0

cloudsmith_cli/cli/commands/repos.py
Before the change, the repository list command didn't return pagination: 
After the change, the pagination is back:
=> ceng-163: Fix repository pagination

.github/workflows/release.yml, .gitignore
* Added zipapp of the cloudsmith-cli
* Added workflow to generate the release with `.pyz` file
=> CENG-260: update-cloudsmith-cli-to-include-zipapp-in-the-release

.envrc, README.md, cloudsmith_cli/cli/commands/login.py, requirements.in, requirements.txt
1. Adds the [`keyring`](https://github.com/jaraco/keyring) dependency
2. Adds utility methods to store SSO access & refresh tokens in the system keyring
3. Updates `.envrc` to:
3.1. install the required python version if missing
3.2. copy `.env.example` to `.env` if `.env` is missing
=> Update CLI to store access and refresh tokens

README.md, cloudsmith_cli/cli/commands/__init__.py, cloudsmith_cli/cli/commands/auth.py, cloudsmith_cli/cli/commands/login.py, cloudsmith_cli/cli/exceptions.py, cloudsmith_cli/cli/saml.py, cloudsmith_cli/cli/tests/test_saml.py, cloudsmith_cli/cli/utils.py, cloudsmith_cli/cli/webserver.py, cloudsmith_cli/core/api/init.py, cloudsmith_cli/core/keyring.py, cloudsmith_cli/core/tests/test_init.py, cloudsmith_cli/core/tests/test_keyring.py, requirements.in, requirements.txt
Adds the `cloudsmith auth` command to authenticate using an organization's configured SAML provider rather than an API key
Access and refresh tokens are stored in the operating system keyring with the timestamp they were generated at. On each command, if the access token is set, the CLI will check if the token should be refreshed prior to executing the command specified
As part of the refresh, the timestamp denoting when the last refresh was attempted will be updated, ensuring we don't repeatedly try to refresh the token on multiple invocations if the refresh failed
=> Add support for SAML authentication

requirements.in, requirements.txt
Now that `keyring` is correctly specified in `setup.py` as of #177, remove it from `requirements.in` meant for dev dependencies
=> Remove keyring from requirements.in

cloudsmith_cli/cli/commands/login.py, cloudsmith_cli/core/api/user.py
* Ensure we are not suppressing relevant error details when logging in hits an error (e.g. a bunch of errors were being suppressed by the raised error message "Invalid username/password").
=> chore: Fix suppressed error detail

README.md, cloudsmith_cli/cli/commands/__init__.py, cloudsmith_cli/cli/commands/auth.py, cloudsmith_cli/cli/commands/login.py, cloudsmith_cli/cli/commands/tokens.py, cloudsmith_cli/cli/tests/commands/test_tokens.py, cloudsmith_cli/core/api/init.py, cloudsmith_cli/core/api/user.py, cloudsmith_cli/core/config.py, requirements.txt, setup.py
For environments that only use SAML for authentication, there currently is no way to programmatically retrieve an existing User API Token. Currently the Cloudsmith CLI allows creating/retrieving User API Tokens only via the `login/token` command which uses basic auth. 
This is my hacky way of getting around these limitations. The `auth --token` command brings consistency between the `login` and `auth` commands, with one caveat: users with an existing token will be asked if they would like to refresh their token.
This also includes the `tokens` command that allows users to list and refresh their token.
To remove the hacky parts of this implementations we need:
1. An API endpoint that allows for the retrieval of an existing token that supports the `Authorization` header without basic auth. …
=> Support for managing User API Tokens via SAML authentication

cloudsmith_cli/cli/commands/auth.py
The initialize_api call is already made via the decorator, rerunning it again ourselves results in config being dropped https://github.com/cloudsmith-io/cloudsmith-cli/blob/e762438bc269e3206ec56c2f87b2ef4f70961ba4/cloudsmith_cli/cli/commands/auth.py#L36
=> fix(no-ticket): drop manual initialize_api as its done in the decorator
